---
title: "Predicting and Downstream Analysis"
output: html_notebook
---

## 1.
Predicting in visceral + beta dataset

```{r}
all.visceral <- scPredict(visceral, all)
all.beta <- scPredict(beta.subset, all)
```

## 2.
Find differentially expressed genes between vulnerable and resistant populations
Sort by adjusted p-value first, then sort by fold change with an arbitrary cutoff (+/- 0.5)

```{r}
vb.combined <- merge(all.visceral, all.beta) # Merge visceral and beta data into one object
Idents(object = vb.combined) <- vb.combined$scpred_prediction # Assign identities based on whether res/vuln
vb.markers <- FindMarkers(vb.combined, ident.1 = "res", ident.2 = "vuln") # DE finds 256 marker genes between res and vuln

# Select by adjusted p-value: finds 21 genes with most significant difference (p-value < 1x10^-100)

vb.pvalue <- vb.markers[which(vb.markers$p_val_adj < 1e-100), ]

# Select by log2FC: finds 12 genes with most significant and greatest fold change differences (+/- 0.5 log2FC )

vb.pvalue.fc <- vb.pvalue[which(vb.pvalue$avg_log2FC > 0.5 | vb.pvalue$avg_log2FC < -0.5), ]

write.csv(vb.pvalue, "~/Documents/R/PredictResistance/genes.pvalue.top21.csv")
write.csv(vb.pvalue.fc, "~/Documents/R/PredictResistance/genes.pvalue.fc.top12.csv")
```

## 3. 
Gene ontology analysis - performed with GOnet (online software)
Gene pathway and function analysis - performed manually


